[package]
name = "iot-device"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.9.2"
rumqttc = "0.25.0"
serde = { version = "1.0.225", features = ["derive"] }
serde_json = "1.0.145"
tokio = { version = "1.47.1", features = ["full"] }
